# ---------------------------------------------------------------------
#-------------------------- PAGES COMPANY -----------------------------
# ---------------------------------------------------------------------

company_create:
   path: /company/create
   controller: App\Controller\CompanyController::create

#---------------------------------------------------------------------
#---------------------------- PAGES USER ------------------------------
# ---------------------------------------------------------------------

user_showall:
     path: /user/showAll
     controller: App\Controller\UserController::showAll

backoffice_user_update:
   path: /backoffice/update/{id}
   controller: App\Controller\UserController::update
   requirements: 
    id: \d+

backoffice:
   path: /backoffice/
   controller: App\Controller\BackofficeController::index


backoffice_challenge:
   path: /backoffice/challenge
   controller: App\Controller\ChallengeController::challengeBack


backoffice_challenge_update:
   path: /backoffice/challenge/update/{id}
   controller: App\Controller\ChallengeController::update
   requirements:
        id: \d+

backoffice_challenge_delete:
   path: /backoffice/challenge/delete/{id}
   controller: App\Controller\ChallengeController::delete
   requirements:
        id: \d+

