# ---------------------------------------------------------------------
#-------------------------- PAGES COMPANY -----------------------------
# ---------------------------------------------------------------------



company_create:
   path: /company/create
   controller: App\Controller\CompanyController::create

<<<<<<< HEAD
# ---------------------------------------------------------------------
#---------------------------- PAGES USER ------------------------------
# ---------------------------------------------------------------------

# user_showall:
#     path: /user/showAll
#     controller: App\Controller\UserController::showAll
=======
backoffice_user_update:
   path: /backoffice/update/{id}
   controller: App\Controller\UserController::update
   requirements: 
    id: \d+

backoffice:
   path: /backoffice/
   controller: App\Controller\BackofficeController::index

>>>>>>> 2fa37a977b78dd4a529441b10f037567fde0a991
