# ---------------------------------------------------------------------
#-------------------------- PAGES COMPANY -----------------------------
# ---------------------------------------------------------------------



company_create:
   path: /company/create
   controller: App\Controller\CompanyController::create

# ---------------------------------------------------------------------
#---------------------------- PAGES USER ------------------------------
# ---------------------------------------------------------------------

# user_showall:
#     path: /user/showAll
#     controller: App\Controller\UserController::showAll
